language: python

matrix:
  include:
    - name: "Python 2.7 on Xenial Linux"
      python: 2.6
      dist: trusty
    - name: "Python 2.7 on Xenial Linux"
      python: 2.7
      dist: precise
    - name: "Python 3.3 on Xenial Linux"
      python: 3.3
      dist: trusty
    - name: "Python 3.4 on Xenial Linux"
      python: 3.4
      dist: xenial
    - name: "Python 3.5 on Xenial Linux"
      python: 3.5
      dist: xenial
    - name: "Python 3.6 on Xenial Linux"
      python: 3.6
      dist: xenial
    - name: "Python 3.7 on Xenial Linux"
      python: 3.7
      dist: xenial
    - name: "Python 3.7.2 on macOS"
      os: osx
      osx_image: xcode10.2
      language: shell
    - name: "Python 3.7 on Windows"
      os: windows
      language: shell
      before_install: choco install python
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH

# command to run tests
script: python setup.py test
